MAPS = {
    "classic" : {
        "file" : "maps/classic.jpg",
        "continents" : [
            {
                "name" : "North America",
                "bonus" : 5,
                "territories" : {"Alaska", "North West Territory", "Greenland", "Alberta", "Ontario", "Quebec", "Western United States", "Eastern United States", "Central America"}
            },
            {
                "name" : "South America",
                "bonus" : 2,
                "territories" : {"Venezuela", "Peru", "Brazil", "Argentina"}
            },
            {
                "name" : "Europe",
                "bonus" : 5,
                "territories" : {"Iceland", "Scandinavia", "Ukraine", "Great Britain", "Northern Europe", "Western Europe", "Southern Europe"}
            },
            {
                "name" : "Africa",
                "bonus" : 3,
                "territories" : {"North Africa", "Egypt", "East Africa", "Congo", "South Africa", "Madagascar"}
            },
            {
                "name" : "Asia",
                "bonus" : 7,
                "territories" : {"Ural", "Siberia", "Yakutsk", "Kamchatka", "Irkutsk", "Mongolia", "Japan", "Afghanistan", "China", "Middle East", "India", "Siam"}
            },
            {
                "name" : "Australia",
                "bonus" : 2,
                "territories" : {"Indonesia", "New Guinea", "Western Australia", "Eastern Australia"}
            }
        ],
        "connections" : {
            "Alaska" : ("North West Territory", "Alberta", "Kamchatka"),
            "North West Territory" : ("Alaska", "Alberta", "Ontario", "Greenland"),
            "Greenland" : ("North West Territory", "Ontario", "Quebec", "Iceland"),
            "Alberta" : ("Alaska", "North West Territory", "Ontario", "Western United States"),
            "Ontario" : ("North West Territory", "Greenland", "Alberta", "Quebec", "Western United States", "Eastern United States"),
            "Quebec" : ("Greenland", "Ontario", "Eastern United States"),
            "Western United States" : ("Alberta", "Ontario", "Eastern United States", "Central America"),
            "Eastern United States" : ("Ontario", "Quebec", "Western United States", "Central America"),
            "Central America" : ("Western United States", "Eastern United States", "Venezuela"),
            "Venezuela" : ("Central America", "Peru", "Brazil"),
            "Peru" : ("Venezuela", "Brazil", "Argentina"),
            "Brazil" : ("Venezuela", "Peru", "Argentina", "North Africa"),
            "Argentina" : ("Peru", "Brazil"),
            "Iceland" : ("Greenland", "Scandinavia", "Great Britain"),
            "Scandinavia" : ("Iceland", "Ukraine", "Great Britain", "Northern Europe"),
            "Ukraine" : ("Scandinavia", "Northern Europe", "Southern Europe", "Ural", "Afghanistan", "Middle East"),
            "Great Britain" : ("Iceland", "Scandinavia", "Northern Europe", "Western Europe"),
            "Northern Europe" : ("Scandinavia", "Ukraine", "Great Britain", "Western Europe", "Southern Europe"),
            "Western Europe" : ("Great Britain", "Northern Europe", "Southern Europe", "North Africa"),
            "Southern Europe" : ("Northern Europe", "Ukraine", "Western Europe", "North Africa", "Egypt", "Middle East"),
            "North Africa" : ("Brazil", "Western Europe", "Southern Europe", "Egypt", "East Africa", "Congo"),
            "Egypt" : ("Southern Europe", "North Africa", "East Africa", "Middle East"),
            "East Africa" : ("North Africa", "Egypt", "Congo", "South Africa", "Madagascar", "Middle East"),
            "Congo" : ("North Africa", "East Africa", "South Africa"),
            "South Africa" : ("Congo", "East Africa", "Madagascar"),
            "Madagascar" : ("East Africa", "South Africa"),
            "Ural" : ("Ukraine", "Siberia", "Afghanistan", "China"),
            "Siberia" : ("Ural", "Yakutsk", "Irkutsk", "Mongolia", "China"),
            "Yakutsk" : ("Siberia", "Kamchatka", "Irkutsk"),
            "Kamchatka" : ("Alaska", "Yakutsk", "Irkutsk", "Mongolia", "Japan"),
            "Irkutsk" : ("Siberia", "Yakutsk", "Kamchatka", "Mongolia"),
            "Mongolia" : ("Siberia", "Kamchatka", "Irkutsk", "Japan", "China"),
            "Japan" : ("Kamchatka", "Mongolia"),
            "Afghanistan" : ("Ukraine", "Ural", "China", "Middle East", "India"),
            "China" : ("Ural", "Siberia", "Mongolia", "Afghanistan", "India", "Siam"),
            "Middle East" : ("Ukraine", "Southern Europe", "Egypt", "East Africa", "Afghanistan", "India"),
            "India" : ("Afghanistan", "China", "Middle East", "Siam"),
            "Siam" : ("China", "India", "Indonesia"),
            "Indonesia" : ("Siam", "New Guinea", "Western Australia"),
            "New Guinea" : ("Indonesia", "Western Australia", "Eastern Australia"),
            "Western Australia" : ("Indonesia", "New Guinea", "Eastern Australia"),
            "Eastern Australia" : ("New Guinea", "Western Australia"),
        },
        "bubbles" : {
            "Alaska" : (44, 94),
            "North West Territory" : (125, 86),
            "Greenland" : (268, 59),
            "Alberta" : (112, 136),
            "Ontario" : (155, 122),
            "Quebec" : (206, 151),
            "Western United States" : (109, 199),
            "Eastern United States" : (195, 188),
            "Central America" : (135, 253),
            "Venezuela" : (170, 288),
            "Peru" : (172, 371),
            "Brazil" : (243, 375),
            "Argentina" : (190, 457),
            "Iceland" : (329, 114),
            "Scandinavia" : (393, 122),
            "Ukraine" : (457, 164),
            "Great Britain" : (326, 179),
            "Northern Europe" : (371, 194),
            "Western Europe" : (340, 260),
            "Southern Europe" : (380, 234),
            "North Africa" : (359, 316),
            "Egypt" : (425, 326),
            "East Africa" : (452, 351),
            "Congo" : (431, 421),
            "South Africa" : (429, 498),
            "Madagascar" : (493, 475),
            "Ural" : (553, 145),
            "Siberia" : (597, 101),
            "Yakutsk" : (644, 77),
            "Kamchatka" : (702, 82),
            "Irkutsk" : (635, 145),
            "Mongolia" : (648, 197),
            "Japan" : (723, 207),
            "Afghanistan" : (536, 214),
            "China" : (644, 252),
            "Middle East" : (489, 305),
            "India" : (583, 302),
            "Siam" : (661, 317),
            "Indonesia" : (656, 414),
            "New Guinea" : (733, 392),
            "Western Australia" : (689, 452),
            "Eastern Australia" : (762, 485)
        }
    }
}